CREATE TABLE TELECOM_MODEL(ID INT AUTO_INCREMENT PRIMARY KEY, PATIENT_ID INT NOT NULL, T_SYSTEM VARCHAR(100), T_VALUE VARCHAR(100), T_USE VARCHAR(100));

CREATE TABLE MESSAGE_MODEL(ID INT AUTO_INCREMENT PRIMARY KEY, BUNDLE_ID VARCHAR(100), ENCOUNTER_ID VARCHAR(100), PATIENT_ID VARCHAR(100), MESSAGE_BODY CLOB);

CREATE TABLE ENCOUNTER_MODEL(ID INT AUTO_INCREMENT PRIMARY KEY, RESOURCE_TYPE VARCHAR(100), IDENTIFIER_SYSTEM VARCHAR(100), IDENTIFIER_VALUE VARCHAR(100), STATUS VARCHAR(100), CLASS_SYSTEM VARCHAR(100),
CLASS_CODE VARCHAR(100), CLASS_DISPLAY VARCHAR(100), TYPE_CODING_SYSTEM VARCHAR(100), TYPE_CODING_CODE VARCHAR(100), TYPE_CODING_DISPLAY VARCHAR(100), SUBJECT_REFERENCE VARCHAR(100), VERSION INT);

CREATE TABLE PATIENT_MODEL(ID INT AUTO_INCREMENT PRIMARY KEY, RESOURCE_TYPE VARCHAR(100), IDENTIFIER_SYSTEM VARCHAR(100), IDENTIFIER_VALUE VARCHAR(100), NAME VARCHAR(100), GENDER VARCHAR(100),
BIRTH_DATE VARCHAR(100), VERSION INT);